language: cpp
compiler: gcc
dist: focal

install:
  - sudo apt-get install -y git libglib2.0-dev libfdt-dev libpixman-1-dev zlib1g-dev

  - sudo apt-get install -y build-essential protobuf-compiler libusb-1.0-0-dev libssl-dev openssl libglib2.0-dev
  - sudo apt-get install -y libboost-dev libudev-dev libtag1-dev libprotobuf-dev libgstreamer1.0-dev gstreamer1.0-plugins-base-apps
  - sudo apt-get install -y gstreamer1.0-plugins-good gstreamer1.0-plugins-bad gstreamer1.0-libav gstreamer1.0-alsa libgstreamer-plugins-base1.0-dev
  - sudo apt-get install -y gstreamer1.0-pulseaudio libfaad-dev libfftw3-dev librtlsdr-dev libairspy-dev libusb-1.0-0-dev mesa-common-dev
  - sudo apt-get install -y libglu1-mesa-dev zlib1g-dev  portaudio19-dev libsndfile1-dev libsamplerate0-dev ofono ofono-dev
  - sudo apt-get install -y ofono-phonesim pulseaudio bluez bluez-obexd pulseaudio-module-bluetooth qtconnectivity5-dev
  - sudo apt-get install -y qml-module-qtbluetooth libkf5bluezqt-dev qml-module-org-kde-bluezqt qtbase5-private-dev libcanberra-dev
  - sudo apt-get install -y libqt5charts5 libqt5charts5-dev qml-module-qtcharts libqt5serialport5-dev
  - sudo apt-get install -y libgconf2-dev libpulse-dev libmp3lame-dev libsoapysdr-dev libmpg123-dev
  - sudo apt-get install -y qt5-default qtdeclarative5-dev qtmultimedia5-dev libqt5multimedia5-plugins
  - sudo apt-get install -y libqt5xmlpatterns5-dev libqt5bluetooth5 qtconnectivity5-dev libqt5charts5 libqt5serialport5
  - sudo apt-get install -y qml-module-qtquick2 qml-module-qtquick-layouts qml-module-qtquick-dialogs qml-module-qtquick-controls2
  - sudo apt-get install -y qml-module-qtquick-extras qml-module-qtquick-window2 qml-module-qtmultimedia qml-module-qt-labs-settings
  - sudo apt-get install -y qml-module-qt-labs-folderlistmodel qml-module-qt-labs-platform qml-module-qtbluetooth qml-module-qtcharts
  - sudo apt-get install -y qml-module-qtgraphicaleffects
    
script:
  - protoc --proto_path=modules/android-auto/headunit/hu/ --cpp_out=modules/android-auto/headunit/hu/generated.x64/ modules/android-auto/headunit/hu/hu.pro
  - mkdir build && cd build
  - qmake ../headunit-desktop.pro
  - make -j8
